/**
 * International dial codes, one entry per country in `COUNTRIES` (lib/countries.ts).
 * Used by PhoneInput's country-code picker. No flag emoji — Windows renders
 * regional-indicator flag emoji as bare two-letter codes instead of a flag
 * glyph, which looks broken; the dial code itself is label enough.
 */
export interface CallingCode {
  iso2: string;
  country: string;
  dialCode: string;
}

export const DEFAULT_CALLING_CODE_ISO2 = 'NG';

export const CALLING_CODES: CallingCode[] = [
  { iso2: 'AF', country: 'Afghanistan', dialCode: '+93' },
  { iso2: 'AL', country: 'Albania', dialCode: '+355' },
  { iso2: 'DZ', country: 'Algeria', dialCode: '+213' },
  { iso2: 'AD', country: 'Andorra', dialCode: '+376' },
  { iso2: 'AO', country: 'Angola', dialCode: '+244' },
  { iso2: 'AG', country: 'Antigua and Barbuda', dialCode: '+1' },
  { iso2: 'AR', country: 'Argentina', dialCode: '+54' },
  { iso2: 'AM', country: 'Armenia', dialCode: '+374' },
  { iso2: 'AU', country: 'Australia', dialCode: '+61' },
  { iso2: 'AT', country: 'Austria', dialCode: '+43' },
  { iso2: 'AZ', country: 'Azerbaijan', dialCode: '+994' },
  { iso2: 'BS', country: 'Bahamas', dialCode: '+1' },
  { iso2: 'BH', country: 'Bahrain', dialCode: '+973' },
  { iso2: 'BD', country: 'Bangladesh', dialCode: '+880' },
  { iso2: 'BB', country: 'Barbados', dialCode: '+1' },
  { iso2: 'BY', country: 'Belarus', dialCode: '+375' },
  { iso2: 'BE', country: 'Belgium', dialCode: '+32' },
  { iso2: 'BZ', country: 'Belize', dialCode: '+501' },
  { iso2: 'BJ', country: 'Benin', dialCode: '+229' },
  { iso2: 'BT', country: 'Bhutan', dialCode: '+975' },
  { iso2: 'BO', country: 'Bolivia', dialCode: '+591' },
  { iso2: 'BA', country: 'Bosnia and Herzegovina', dialCode: '+387' },
  { iso2: 'BW', country: 'Botswana', dialCode: '+267' },
  { iso2: 'BR', country: 'Brazil', dialCode: '+55' },
  { iso2: 'BN', country: 'Brunei', dialCode: '+673' },
  { iso2: 'BG', country: 'Bulgaria', dialCode: '+359' },
  { iso2: 'BF', country: 'Burkina Faso', dialCode: '+226' },
  { iso2: 'BI', country: 'Burundi', dialCode: '+257' },
  { iso2: 'CV', country: 'Cabo Verde', dialCode: '+238' },
  { iso2: 'KH', country: 'Cambodia', dialCode: '+855' },
  { iso2: 'CM', country: 'Cameroon', dialCode: '+237' },
  { iso2: 'CA', country: 'Canada', dialCode: '+1' },
  { iso2: 'CF', country: 'Central African Republic', dialCode: '+236' },
  { iso2: 'TD', country: 'Chad', dialCode: '+235' },
  { iso2: 'CL', country: 'Chile', dialCode: '+56' },
  { iso2: 'CN', country: 'China', dialCode: '+86' },
  { iso2: 'CO', country: 'Colombia', dialCode: '+57' },
  { iso2: 'KM', country: 'Comoros', dialCode: '+269' },
  { iso2: 'CG', country: 'Congo (Republic of the)', dialCode: '+242' },
  { iso2: 'CR', country: 'Costa Rica', dialCode: '+506' },
  { iso2: 'CI', country: "Côte d'Ivoire", dialCode: '+225' },
  { iso2: 'HR', country: 'Croatia', dialCode: '+385' },
  { iso2: 'CU', country: 'Cuba', dialCode: '+53' },
  { iso2: 'CY', country: 'Cyprus', dialCode: '+357' },
  { iso2: 'CZ', country: 'Czechia', dialCode: '+420' },
  { iso2: 'CD', country: 'Democratic Republic of the Congo', dialCode: '+243' },
  { iso2: 'DK', country: 'Denmark', dialCode: '+45' },
  { iso2: 'DJ', country: 'Djibouti', dialCode: '+253' },
  { iso2: 'DM', country: 'Dominica', dialCode: '+1' },
  { iso2: 'DO', country: 'Dominican Republic', dialCode: '+1' },
  { iso2: 'EC', country: 'Ecuador', dialCode: '+593' },
  { iso2: 'EG', country: 'Egypt', dialCode: '+20' },
  { iso2: 'SV', country: 'El Salvador', dialCode: '+503' },
  { iso2: 'GQ', country: 'Equatorial Guinea', dialCode: '+240' },
  { iso2: 'ER', country: 'Eritrea', dialCode: '+291' },
  { iso2: 'EE', country: 'Estonia', dialCode: '+372' },
  { iso2: 'SZ', country: 'Eswatini', dialCode: '+268' },
  { iso2: 'ET', country: 'Ethiopia', dialCode: '+251' },
  { iso2: 'FJ', country: 'Fiji', dialCode: '+679' },
  { iso2: 'FI', country: 'Finland', dialCode: '+358' },
  { iso2: 'FR', country: 'France', dialCode: '+33' },
  { iso2: 'GA', country: 'Gabon', dialCode: '+241' },
  { iso2: 'GM', country: 'Gambia', dialCode: '+220' },
  { iso2: 'GE', country: 'Georgia', dialCode: '+995' },
  { iso2: 'DE', country: 'Germany', dialCode: '+49' },
  { iso2: 'GH', country: 'Ghana', dialCode: '+233' },
  { iso2: 'GR', country: 'Greece', dialCode: '+30' },
  { iso2: 'GD', country: 'Grenada', dialCode: '+1' },
  { iso2: 'GT', country: 'Guatemala', dialCode: '+502' },
  { iso2: 'GN', country: 'Guinea', dialCode: '+224' },
  { iso2: 'GW', country: 'Guinea-Bissau', dialCode: '+245' },
  { iso2: 'GY', country: 'Guyana', dialCode: '+592' },
  { iso2: 'HT', country: 'Haiti', dialCode: '+509' },
  { iso2: 'HN', country: 'Honduras', dialCode: '+504' },
  { iso2: 'HU', country: 'Hungary', dialCode: '+36' },
  { iso2: 'IS', country: 'Iceland', dialCode: '+354' },
  { iso2: 'IN', country: 'India', dialCode: '+91' },
  { iso2: 'ID', country: 'Indonesia', dialCode: '+62' },
  { iso2: 'IR', country: 'Iran', dialCode: '+98' },
  { iso2: 'IQ', country: 'Iraq', dialCode: '+964' },
  { iso2: 'IE', country: 'Ireland', dialCode: '+353' },
  { iso2: 'IL', country: 'Israel', dialCode: '+972' },
  { iso2: 'IT', country: 'Italy', dialCode: '+39' },
  { iso2: 'JM', country: 'Jamaica', dialCode: '+1' },
  { iso2: 'JP', country: 'Japan', dialCode: '+81' },
  { iso2: 'JO', country: 'Jordan', dialCode: '+962' },
  { iso2: 'KZ', country: 'Kazakhstan', dialCode: '+7' },
  { iso2: 'KE', country: 'Kenya', dialCode: '+254' },
  { iso2: 'KI', country: 'Kiribati', dialCode: '+686' },
  { iso2: 'KW', country: 'Kuwait', dialCode: '+965' },
  { iso2: 'KG', country: 'Kyrgyzstan', dialCode: '+996' },
  { iso2: 'LA', country: 'Laos', dialCode: '+856' },
  { iso2: 'LV', country: 'Latvia', dialCode: '+371' },
  { iso2: 'LB', country: 'Lebanon', dialCode: '+961' },
  { iso2: 'LS', country: 'Lesotho', dialCode: '+266' },
  { iso2: 'LR', country: 'Liberia', dialCode: '+231' },
  { iso2: 'LY', country: 'Libya', dialCode: '+218' },
  { iso2: 'LI', country: 'Liechtenstein', dialCode: '+423' },
  { iso2: 'LT', country: 'Lithuania', dialCode: '+370' },
  { iso2: 'LU', country: 'Luxembourg', dialCode: '+352' },
  { iso2: 'MG', country: 'Madagascar', dialCode: '+261' },
  { iso2: 'MW', country: 'Malawi', dialCode: '+265' },
  { iso2: 'MY', country: 'Malaysia', dialCode: '+60' },
  { iso2: 'MV', country: 'Maldives', dialCode: '+960' },
  { iso2: 'ML', country: 'Mali', dialCode: '+223' },
  { iso2: 'MT', country: 'Malta', dialCode: '+356' },
  { iso2: 'MH', country: 'Marshall Islands', dialCode: '+692' },
  { iso2: 'MR', country: 'Mauritania', dialCode: '+222' },
  { iso2: 'MU', country: 'Mauritius', dialCode: '+230' },
  { iso2: 'MX', country: 'Mexico', dialCode: '+52' },
  { iso2: 'FM', country: 'Micronesia', dialCode: '+691' },
  { iso2: 'MD', country: 'Moldova', dialCode: '+373' },
  { iso2: 'MC', country: 'Monaco', dialCode: '+377' },
  { iso2: 'MN', country: 'Mongolia', dialCode: '+976' },
  { iso2: 'ME', country: 'Montenegro', dialCode: '+382' },
  { iso2: 'MA', country: 'Morocco', dialCode: '+212' },
  { iso2: 'MZ', country: 'Mozambique', dialCode: '+258' },
  { iso2: 'MM', country: 'Myanmar', dialCode: '+95' },
  { iso2: 'NA', country: 'Namibia', dialCode: '+264' },
  { iso2: 'NR', country: 'Nauru', dialCode: '+674' },
  { iso2: 'NP', country: 'Nepal', dialCode: '+977' },
  { iso2: 'NL', country: 'Netherlands', dialCode: '+31' },
  { iso2: 'NZ', country: 'New Zealand', dialCode: '+64' },
  { iso2: 'NI', country: 'Nicaragua', dialCode: '+505' },
  { iso2: 'NE', country: 'Niger', dialCode: '+227' },
  { iso2: 'NG', country: 'Nigeria', dialCode: '+234' },
  { iso2: 'KP', country: 'North Korea', dialCode: '+850' },
  { iso2: 'MK', country: 'North Macedonia', dialCode: '+389' },
  { iso2: 'NO', country: 'Norway', dialCode: '+47' },
  { iso2: 'OM', country: 'Oman', dialCode: '+968' },
  { iso2: 'PK', country: 'Pakistan', dialCode: '+92' },
  { iso2: 'PW', country: 'Palau', dialCode: '+680' },
  { iso2: 'PS', country: 'Palestine', dialCode: '+970' },
  { iso2: 'PA', country: 'Panama', dialCode: '+507' },
  { iso2: 'PG', country: 'Papua New Guinea', dialCode: '+675' },
  { iso2: 'PY', country: 'Paraguay', dialCode: '+595' },
  { iso2: 'PE', country: 'Peru', dialCode: '+51' },
  { iso2: 'PH', country: 'Philippines', dialCode: '+63' },
  { iso2: 'PL', country: 'Poland', dialCode: '+48' },
  { iso2: 'PT', country: 'Portugal', dialCode: '+351' },
  { iso2: 'QA', country: 'Qatar', dialCode: '+974' },
  { iso2: 'RO', country: 'Romania', dialCode: '+40' },
  { iso2: 'RU', country: 'Russia', dialCode: '+7' },
  { iso2: 'RW', country: 'Rwanda', dialCode: '+250' },
  { iso2: 'KN', country: 'Saint Kitts and Nevis', dialCode: '+1' },
  { iso2: 'LC', country: 'Saint Lucia', dialCode: '+1' },
  { iso2: 'VC', country: 'Saint Vincent and the Grenadines', dialCode: '+1' },
  { iso2: 'WS', country: 'Samoa', dialCode: '+685' },
  { iso2: 'SM', country: 'San Marino', dialCode: '+378' },
  { iso2: 'ST', country: 'Sao Tome and Principe', dialCode: '+239' },
  { iso2: 'SA', country: 'Saudi Arabia', dialCode: '+966' },
  { iso2: 'SN', country: 'Senegal', dialCode: '+221' },
  { iso2: 'RS', country: 'Serbia', dialCode: '+381' },
  { iso2: 'SC', country: 'Seychelles', dialCode: '+248' },
  { iso2: 'SL', country: 'Sierra Leone', dialCode: '+232' },
  { iso2: 'SG', country: 'Singapore', dialCode: '+65' },
  { iso2: 'SK', country: 'Slovakia', dialCode: '+421' },
  { iso2: 'SI', country: 'Slovenia', dialCode: '+386' },
  { iso2: 'SB', country: 'Solomon Islands', dialCode: '+677' },
  { iso2: 'SO', country: 'Somalia', dialCode: '+252' },
  { iso2: 'ZA', country: 'South Africa', dialCode: '+27' },
  { iso2: 'KR', country: 'South Korea', dialCode: '+82' },
  { iso2: 'SS', country: 'South Sudan', dialCode: '+211' },
  { iso2: 'ES', country: 'Spain', dialCode: '+34' },
  { iso2: 'LK', country: 'Sri Lanka', dialCode: '+94' },
  { iso2: 'SD', country: 'Sudan', dialCode: '+249' },
  { iso2: 'SR', country: 'Suriname', dialCode: '+597' },
  { iso2: 'SE', country: 'Sweden', dialCode: '+46' },
  { iso2: 'CH', country: 'Switzerland', dialCode: '+41' },
  { iso2: 'SY', country: 'Syria', dialCode: '+963' },
  { iso2: 'TJ', country: 'Tajikistan', dialCode: '+992' },
  { iso2: 'TZ', country: 'Tanzania', dialCode: '+255' },
  { iso2: 'TH', country: 'Thailand', dialCode: '+66' },
  { iso2: 'TL', country: 'Timor-Leste', dialCode: '+670' },
  { iso2: 'TG', country: 'Togo', dialCode: '+228' },
  { iso2: 'TO', country: 'Tonga', dialCode: '+676' },
  { iso2: 'TT', country: 'Trinidad and Tobago', dialCode: '+1' },
  { iso2: 'TN', country: 'Tunisia', dialCode: '+216' },
  { iso2: 'TR', country: 'Turkey', dialCode: '+90' },
  { iso2: 'TM', country: 'Turkmenistan', dialCode: '+993' },
  { iso2: 'TV', country: 'Tuvalu', dialCode: '+688' },
  { iso2: 'UG', country: 'Uganda', dialCode: '+256' },
  { iso2: 'UA', country: 'Ukraine', dialCode: '+380' },
  { iso2: 'AE', country: 'United Arab Emirates', dialCode: '+971' },
  { iso2: 'GB', country: 'United Kingdom', dialCode: '+44' },
  { iso2: 'US', country: 'United States', dialCode: '+1' },
  { iso2: 'UY', country: 'Uruguay', dialCode: '+598' },
  { iso2: 'UZ', country: 'Uzbekistan', dialCode: '+998' },
  { iso2: 'VU', country: 'Vanuatu', dialCode: '+678' },
  { iso2: 'VA', country: 'Vatican City', dialCode: '+379' },
  { iso2: 'VE', country: 'Venezuela', dialCode: '+58' },
  { iso2: 'VN', country: 'Vietnam', dialCode: '+84' },
  { iso2: 'YE', country: 'Yemen', dialCode: '+967' },
  { iso2: 'ZM', country: 'Zambia', dialCode: '+260' },
  { iso2: 'ZW', country: 'Zimbabwe', dialCode: '+263' },
];
